export default [
    {
        id: 1,
        name: "Corey Taylor",
        email: "Slip_N_Sour@yahoo.com",
        role: "Singer/Songwriter",
        age: 45,
        birthplace: "Des Moines, Iowa",
        acts: "Slipknot, Stone Sour",
    },
    {
        id: 2,
        name: "Chad Gray",
        email: "Mudvayne_HY@verizon.net",
        role: "Singer/Songwriter",
        age: 47,
        birthplace: "Latham, Illinois",
        acts: "Mudvayne, Hellyeah",
    },
    {
        id: 3,
        name: "Ryan Clark",
        email: "DemonHunterVocs@hotmail.com",
        role: "Singer/Songwriter",
        age: 40,
        birthplace: "Woody California",
        acts: "Demon Hunter",
    },
    {
        id: 4,
        name: "Darrell Lance Abbott",
        email: "DimeBag333@gmail.com",
        role: "Guitarist",
        age: 38,
        birthplace: "Columbus, Ohio",
        acts: "Pantera, Damageplan",
    },
    {
        id: 5,
        name: "Vincent Paul Abbott",
        email: "Drummer_Vinnie@aol.com",
        role: "Drummer",
        age: 54,
        birthplace: "Albeline, Texas",
        acts: "Pantera, Hellyeah",
    },
];